contentdir = "content"
publishdir = "public"
builddrafts = false
canonifyurls = true
title = "ğŸ‘ï¸ v ğŸ‘ï¸â€"
author = "xD"
theme = "hugo-theme-mini"
#disqusShortname = "xD's blog"
defaultContentLanguage= "zh"
languageCode= "zh-ch"
hasCJKLanguage= true
enableEmogi=true

[markup]
[highlight]
guessSyntax= true
[tableOfContents]
endLevel= 3
ordered= false
startLevel= 2
# needed to render raw HTML (e.g. <sub>, <sup>, <kbd>, <mark>)
[goldmark]
[renderer]
unsafe= true

[blackfriday]
angledQuotes = true
hrefTargetBlank = false

[indexes]
  category = "categories"
  tag = "tags"

[params]
  mainSections = ["post"]
  search_engine = false
  google_analytics_id = "G-DQ0VSSVGL6"
  #twitter_username = "username"
  paginate = 100
  copyright= ''
  math=true
  showToc= true
  description= "éšä¾¿è¯´è¯´"
  author="xD"
  bio="éšä¾¿è¯´è¯´"
showPowerBy=false

